### ISSUE TITLE
Crash SVPGraph.cpp line 704

### ISSUE THREAD

**Issue by SebGrinke** [BlenderSleuth/FlyingNavSystemSupport#1]
**Describe the bug**
I implemented a flying drone in my UE4.26 game following your tutorial. I'm getting a repeated crash with the stack below. It seems to happen when I climb a ladder and am above the drone's position.

LoginId:dd59376449c3f9f4233f7496f3e650ad
EpicAccountId:be6a9c659a1c4bc2871ff125ae075bbc

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000112999d23b4

UE4Editor_FlyingNavSystem!FSVOPathfindingGraph::ProcessSingleLazyThetaStarNode() [D:\Build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\FlyingNavSystem\Source\FlyingNavSystem\Private\SVOGraph.cpp:704]
UE4Editor_FlyingNavSystem!FSVOPathfindingGraph::FindSVOPath() [D:\Build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\FlyingNavSystem\Source\FlyingNavSystem\Private\SVOGraph.cpp:863]
UE4Editor_FlyingNavSystem!FSVOPathfindingGraph::FindPath() [D:\Build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\FlyingNavSystem\Source\FlyingNavSystem\Private\SVOGraph.cpp:972]
UE4Editor_FlyingNavSystem!AFlyingNavigationData::FindPath() [D:\Build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\FlyingNavSystem\Source\FlyingNavSystem\Private\FlyingNavigationData.cpp:1099]
UE4Editor_NavigationSystem
UE4Editor_AIModule
UE4Editor_AIModule
UE4Editor_AIModule
UE4Editor_AIModule
UE4Editor_AIModule
UE4Editor_AIModule
UE4Editor_AIModule
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**To Reproduce**
It's in my game so can't give you this easily

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4033291/127938119-75a94971-b6a4-4e91-8e0f-8ec06a8a85a7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.0]

**Additional context**

**Comment by SebGrinke** [comment]
Looks like this was caused by "Allow partial path" being ticked in one of my MoveTo nodes. I've unticked that and now it's not crashing any more.

**Comment by BlenderSleuth** [comment]
Thanks for the bug report, I'm looking into it now

**Comment by BlenderSleuth** [comment]
As an update, it appears to be an issue with the lazy theta* algorithm, A* seems unaffected at this point

**Comment by BlenderSleuth** [comment]
Fixed with 1.0.7
