### ISSUE TITLE
Crash while running game with one flying enemy in UnrealEd

### ISSUE THREAD

**Issue by SebGrinke** [BlenderSleuth/FlyingNavSystemSupport#2]
<img width="859" alt="FlyingNavCrash2" src="https://user-images.githubusercontent.com/4033291/128262935-e0f2b3be-2291-4a7c-a742-64f62bf1cc8b.PNG">
<img width="1137" alt="FlyingNavCrash2B" src="https://user-images.githubusercontent.com/4033291/128262945-2dcb4c21-c21a-470f-a48a-c1a76d26ae64.PNG">

**Comment by BlenderSleuth** [comment]
Fixed with 1.0.7
