### ISSUE TITLE
UE4 crash during play in Editor

### ISSUE THREAD

**Issue by SebGrinke** [BlenderSleuth/FlyingNavSystemSupport#3]
<img width="1078" alt="NewBug" src="https://user-images.githubusercontent.com/4033291/128645075-79409597-8590-4c22-ada9-81d938e5a748.PNG">

**Comment by BlenderSleuth** [comment]
Hey, thanks very much for these reports! The marketplace update fixing the issue is taking longer than expected to come through, but it shouldn't be too long before you can update

**Comment by BlenderSleuth** [comment]
Fixed with 1.0.7
